[workspace]
resolver = "3"
members = ["smolos", "kernel", "hal_interface", "display"]

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
