[package]
authors = ["Nicolas SIMON <nicolas.simon6790@gmail.com>"]
name = "SmolOS"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.2", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7.0" }
cortex-m-semihosting = "0.5.0"
panic-semihosting = "0.6.0"
embassy-stm32 = { version = "0.3.0", features = ["memory-x", "stm32f769ni", "single-bank"] }

[[bin]]
test = false
name = "SmolOS"


[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
