[package]
name = "display"
version = "0.1.0"
edition = "2024"

[dependencies]
hal_interface = { path = "../hal_interface" }
heapless = "0.9.1"

[lib]
name = "display"
test = false
doctest = false
bench = false
